pub mod app;
#[cfg(feature = "browser")]
pub mod browser;
pub mod diff;
#[cfg(not(feature = "browser"))]
pub mod git;
#[cfg(feature = "browser")]
#[path = "browser_git.rs"]
pub mod git;
pub mod input;
#[cfg(not(feature = "browser"))]
pub mod logger;
#[cfg(feature = "browser")]
#[path = "browser_logger.rs"]
pub mod logger;
pub mod syntax;
pub mod ui;
#[cfg(not(feature = "browser"))]
pub mod watcher;
